apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: default
spec:
  ports:
    - name: http-collector
      port: 14268
      protocol: TCP
      targetPort: 14268
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jaeger-collector
  namespace: default
subsets:
  - addresses:
      - ip: 172.31.8.204  # <-- Replace with EC2 private IP
    ports:
      - port: 14268

