apiVersion: v1
kind: Service
metadata:
  name: node-todo-service
spec:
  type: ClusterIP
  selector:
    app: node-todo
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 9464
      targetPort: 9464
